### ISSUE TITLE
Settings for live streams affecting quality

### ISSUE THREAD

**Issue by MrPedroG** [vonH/plugin.video.iplayerwww#321]
This is what I am experiencing with live BBC One :
- The only CDN that works is Limelight. Any other setting gives me an error (fails to connect).
- HSL protocol plays in 720p, but only for a few seconds - the it just stops permanently (no matter how long you leave it it does not resume)
- DASH protocol plays flawlessly, but only in 540p. I have done an internet speed test and the bandwidth is plenty for much higher resolutions.

Is this normal? Any ideas how I can get 720p to work?

Thanks!

**Comment by CaptainTK** [comment]
Sorry for the late reply, please post these kind of questions in the [forum](https://forum.kodi.tv/showthread.php?tid=239378).

It does not matter how fast your internet connection is. All that matters is how fast your ISP is connected to the servers providing the streams. In some regions, you can only get 540p, which would also explain why HLS stop playing/starts buffering at 720p because it simply runs out of data.

To be frank: This all sounds a bit like you were not in the UK. If that is the case, there is no support for your questions. This add-on must only be used within the UK.
