### ISSUE TITLE
listings not updating [3.0.52] 

### ISSUE THREAD

**Issue by splace** [vonH/plugin.video.iplayerwww#358]
am worried that my kodi Krypton is now unable to get fixes for listing format changes?

i'm stuck on kodi 17 due to newer builds not supported on my hardware.

**Comment by CaptainTK** [comment]
I am sorry to say, but 3.0.x is no longer supported. Since the release of Kodi 19 introduced Python 3 it has become challenging to manage older add-ons due to the neccessity of multiple Kodi installs on a development system or the use of virtual machines. Also, the 3.0.x code of the add-on still supported both HLS and DASH streams, while 4+ relies on DASH only. So the maintenance effort for the 3.0.x version would be a multiple of the efforts required for 4.0.x.

Since Kodi 19 was released in February 2021 already, I will no longer provide updates to the add-on for 18 and older. I take your message as a sign that it really stopped working now, so I will prepare to mark it as broken in the official repo.

**Comment by splace** [comment]
>  mark it as broken in the official repo


im not SURE its listing format change is what happened

<feel free to not reply>

seems to me bbc has to support a lot of old smart tv's etc. which points against this. unless you know better. i understand not maintaining this, but could it be simply some assumptions in the code have become invalid when maybe the code in smart tv's have made commmon but different assumptions that enable the smart tv's to still get listings? or maybe a versioned/legacy mode. (just wondering out loud.)

</feel free to not reply>

**Comment by CaptainTK** [comment]
There have been changes to the website which broke the current (4.x) version of the add-on, and which were fixed in the latest updates. It is safe to assume that the same holds for previous versions.

However, since the code base of these two branches has diverged for quite some time now, it is not a matter of copy and paste to fix the old version.

Apps on Smart TVs are completely unrelated how this add-on works.
