### ISSUE TITLE
Add support for Trakt

### ISSUE THREAD

**Issue by axelsimon** [vonH/plugin.video.iplayerwww#359]
It would be great to support trakt.tv, the way [Elementum](https://github.com/elgatito/plugin.video.elementum/) does for example.

Having to manually enter each episode watched on Trakt is a bit of shame considering how convenient it is when Kodi does it for you automatically :)

**Comment by CaptainTK** [comment]
Shouldn’t [this add-on](https://kodi.wiki/view/Add-on:Trakt) take care of this for all content that you watch using Kodi?

**Comment by axelsimon** [comment]
That's a good point. Not sure why i'm not using that. I'll double-check, closing this for now.

**Comment by axelsimon** [comment]
I'm reopening this. After checking, i'm using the Trakt add-on and it works for everything else (as far is a can tell) but not for the iplayer add-on.

**Comment by kevwag** [comment]
@axelsimon There's a reason the Kodi Trakt addon doesn't work with iPlayer and it's the same reason that implementing Trakt into iPlayer would be difficult, if not impossible:
Whether intentionally or not, the Series/Season formats on iPlayer confuse Metadata databases such as Trakt, IMDB, TMDB etc because the BBC often change the way seasons are presented, particularly with shows they've licensed from other networks.

For example:  Trakt lists the 2019 series "Darkness: Those Who Kill" as having 3 seasons. On iPlayer the BBC have treated each season as a show in its own right with one season each and  the shows named "Darkness: Those Who Kill", "Lost: Those Who Kill" and "Blinded: Those Who Kill".

This is common practice on iPlayer as well as combining seasons / episodes into larger entities than the originally released formats, along other inconsistencies. Incorporating Trakt really isn't viable because its operation would be sketchy at best and would more than likely cause more problems than it solves.

Elementum works well with Trakt because it is essentially a torrent based system and for obvious reasons, most torrents tend to be named in the same convention as used on the metadata sites.

**Comment by axelsimon** [comment]
@kevwag Thanks for your detailed answer. It makes sense. Some shows do follow the "Show Name"/Series {1,2,3} format, but the issue you're describing is probably too prevalent to make a trakt integration worth attempting. Too bad :)

**Comment by kevwag** [comment]
@axelsimon even when shows do conform to the _**Show/Season/Episode**_ format, you'll often find that the BBC have merged two half-hour episodes into a single, hour-long episode (or vice-versa) which again, will cause the episode numbering to differ from the Trakt DB.
I do occasionally get mis-id'd Trakt issues with torrent based addons but they're pretty rare, it usually results in a rogue show or series that I never heard of, randomly appearing in my "watching/progress" list

**Comment by CaptainTK** [comment]
Thanks for the confirmation of what I already thought. This will not be implemented.
