### ISSUE TITLE
Watching and Recommendations fail with error.

### ISSUE THREAD

**Issue by dimkroon** [vonH/plugin.video.iplayerwww#374]
Just to note that these lists are now broken. I quick check revealed that the data structure the BBC returns has again changed. 
I'll fix it when I've bit  more time.

**Comment by CaptainTK** [comment]
I believe this should do the trick, at least as a quick fix. I don't know if this has any side effects, though. Would be great if you could take a look before releasing it to the public.

**Comment by dimkroon** [comment]
Sorry, I'm very busy at the moment; have to meet a few deadlines. Hope to have bit more time next weekend.

**Comment by dimkroon** [comment]
Unfortunately there were some side effects.
- Resume from watching did not resume at the correct time. As it happened, the new field `progress` appears to be progress as a percentage and as such cannot be a direct replacement for the previously used `offset`.
- Since field `programme['count']` is no longer available, context menu 'View all episode' is never added to list items of programmes with multiple episodes.

Some additional changes are suggested in PR #375

**Comment by kevwag** [comment]
I noticed some issues with the watchlist myself, it appeared to be my own actions that broke it.
I browsed to a series via the A-Z navigation menu, I then used "Mark as watched" from the context menu on the episodes I've already seen, hoping that this would make the next unwatched episode appear in the "Watching" section. This did not work as when I tried to open "Watching" it threw an error and wouldn't open.

Nothing I could do in the addon (including uninstalling and reinstalling) would fix the problem. I managed to fix it by opening iPlayer on my Roku box and removing the show from the watching list on there. After restarting Kodi, the Watching page was working again.

If integration is something you're still working on, would it be possible for the addon to display watched markers from BBC rather than local markers from the skin, or maybe the option to choose between the two in the options menu?

**Comment by dimkroon** [comment]
> I noticed some issues with the watchlist myself, it appeared to be my own actions that broke it.
I browsed to a series via the A-Z navigation menu, I then used "Mark as watched" from the context menu on the episodes I've already seen, hoping that this would make the next unwatched episode appear in the "Watching" section. This did not work as when I tried to open "Watching" it threw an error and wouldn't open.

As you've noticed, the "Mark as watched" context menu is a pure Kodi thing and has no effect on iplayer. It is in fact so very much unrelated that it's nigh impossible to have been the cause of the error you got in "Watching". I think it's more likely that parsing the data of that particular episode failed.

It would be very helpful if you could try to reproduce the error by adding that episode again, let us know what the exact error is and send a debug log.
Note: Regarding data, there is a distinct difference between episode that are partly watched (which you can continue), or episodes that are listed as the next episode to watch.

**Comment by dimkroon** [comment]
I had a similar error on the Watching list the other night, might be the same issue. 
If it is, it would be very hard to reproduce.

**Comment by CaptainTK** [comment]
Let's assume this fixed it and close here. If the problem persists with 4.1.2 (to be released soon), please reopen @kevwag.

**Comment by kevwag** [comment]
@CaptainTK The "Continue Watching" part has been ok ever since, the "Added / Watchlist" however does produce a similar error, I've never been able to access this menu in the addon, anything in there would have been added via an official BBC front-end, probably the website itself.
