### ISSUE TITLE
aired info

### ISSUE THREAD

**Issue by primaeval** [vonH/plugin.video.iplayerwww#51]
Thanks for merging my changes. 

I see you brought back the highlight groups. I purposely skipped them because there is no aired info. I thought it made more sense to go into down into the group folder where all the aired info is intact. It doesn't mirror the BBC site exactly but it is consistent. I know its a change for some users but if they rely on aired info for finding new programs they will be disappointed.

**Comment by CaptainTK** [comment]
There are shows which simply don't have an aired date. Thus, nobody can ever rely on every episode having a valid aired date.

Especially with Highlights, I believe it is better to give as many direct options as possible, rather than forcing users to dig in deeper.

Sorry, but I will close this one.

**Comment by primaeval** [comment]
If you really want the expanded groups in the main page you could grab the group pages for aired info, parse it and use that for the group items.

**Comment by CaptainTK** [comment]
What for? The expanded groups on the website also don't have an aired date. Some have a synopsis, some don't. They are just brief links to shows with no detailed description.

Why should the add-on give more information than the website?

**Comment by CaptainTK** [comment]
One more thing just came to my mind. You said above, that "if they repy on aired info for finding new programmes they will be disappointed". Why would they be? In this case, the programmes without an aired info would show up last, so they don't appear "new". These users would get exactly the same "new" programmes with aired info as in your original implementation. There are just a couple of additional seemingly old programmes. If they decide to take a look at one of the collections, they will get the correct aired info and recognize the shows as new.

So I don't see what harm the additional programmes with limited information will do.

**Comment by primaeval** [comment]
I use the Highlights page sorted by date as an RSS feed of new recommended programmes. I only scan the top few because I have seen the rest earlier.

There are 15 programmes in there today with no aired date. I agree they are at the bottom but it stops me looking for them in the group lists if I see them in the Highlights.

I love consistency. ;)

**Comment by CaptainTK** [comment]
Consistency is overrated. :)

I can see your use case now. Would you prefer if programmes without an aired date would disappear completely? I am thinking about a new option in preferences and a simple check for that in AddMenuEntry.

**Comment by primaeval** [comment]
An occasional missing aired date is ok as far as I am concerned. The 1970 date needs to be changed though: there are quite a few programmes from before then so it messes up the ordering.

I think that the group sections in Highlights should be left out, so you can go into their folders and see all the group episodes there. They are really just tasters of what's in the group folders: partial views if you like. As the collections are listed at the top, users should be able to find them easily enough. 

I thought that bold was enough to indicate a collection without the "Collection:" prefix and just a number in brackets was enough for the count. I haven't got any users here to see if this is obvious enoughm but it looked more readable and less cluttered to me.

**Comment by CaptainTK** [comment]
I agree on 1970. I always wanted to use a date in the future, but it is more sensible not to fill it at all


However, I disagree on the groups in Highlights. When I use the addon, I want to get as many choices as possible without the need to dig on deep. This us a different use case than yours. Plus, your point about

**Comment by CaptainTK** [comment]
ctd - stupid mobile

Plus, your point about users going into the collections is invalid. You can do that irrespective of the group episodes being displayed or not.

As for the display: My goal is to be as close as possible to the website. That's why there is the "Collection" prefix. Also, search groups have an unknown number of programmes, which is why just showing a number doesn't work.

**Comment by primaeval** [comment]
If you really want to have all the group episodes I think you should grab the info from the group and most popular pages. Maybe call ScrapeEpisodes with a list of the program ids as a filter for just those episodes. Then the aired info and thumbnails would show up.

I agree: no aired info as opposed to 1970 is the correct thing to do.

**Comment by CaptainTK** [comment]
First of all I don't think that is a good idea because this kind of scraping beyond the actual page may quickly backfire. For instance, how about deep scraping in A-Z? Currently there is no aired date, no description, no icon and no info about the number of available episodes there.

Secondly, scraping three additional pages (usualky there are three groups) will slow down Highlights substantially. On my computer about 95% of the processing time is just loading the HTML page.

So once again: If these entries irritate you, it should be easy to optionally remove them together with all other content without aired info.

**Comment by primaeval** [comment]
I agree 3 more pages would be a bit slow, maybe too slow for us rpi users. ;)

The A-Z section is always in groups as far as I can see, so there is no need for aired dates.

An occasional missing aired date in Categories or Search wouldn't be too bad. It is better not have the aired date than leave out some obscure program from the ancient past you were searching for.

Therefore, if you want to add a Settings switch for ignoring episodes with no aired date, I think it should just be for Highlights.

I get a nice warm completed feeling when I can see all the episodes with aired dates and thumbnails. As an engineer, I can't help but want to fix things. :)

**Comment by CaptainTK** [comment]
I've added the optional suppression in 800d3e0357bb496d0c7656cfd64b971cf1204e18. Highlights looks quite empty right now as there is a lot of these episodes in groups today.

**Comment by primaeval** [comment]
Thanks. I like it that way but I agree many would like the same programmes as on the iplayer site.
