### ISSUE TITLE
ScrapeEpisodes future proofing

### ISSUE THREAD

**Issue by primaeval** [vonH/plugin.video.iplayerwww#52]
If the BBC start pretty printing the episode pages ScrapeEpisodes will fail. Could you have a look at the best way to change the search spaces to a wildcard, maybe the .+? pattern like ListHighlights.

**Comment by CaptainTK** [comment]
Good point!

**Comment by CaptainTK** [comment]
I don't think there is a lot of potential for pretty printing to break ScrapeEpisodes. It mostly relies on re.match of rather simple search terms, which is a better design than ListHighlights.

**Comment by primaeval** [comment]
The last break was a <a\nhref. That's quite a wierd place for a new line. There are a lot of spaces in ScrapeEpisodes that could end up as new lines.

**Comment by CaptainTK** [comment]
Correct, but IIRC that was in one of the huge <a...> blocks containing a lot of information. That's different for ScrapeEpisodes where the information in the HTML is more or less in single tags/spans/divs/whatever.

So theoretically we could change all spaces to .+?, but this makes the regexps more generic and also increases the risk of failure by matching almost everything. Note that the runtime should increase, the more generic the regexp because there are so many more possible matches. Thus, changing every space to .+? is not advisable. One option might be to replace all spaces with a regex which allows spaces and newlines, but what if an additional attribute like a special font is introduced?

The good thing about your design in ScrapeEpisodes is that the function will terminate properly even if some re.match fail. That also means there cannot be a catastrophic failure any more. That being. Said, there will be changes which require a fix for sure, but I find it very hard to predict what that might be.

On a side note: By accident, I found out where the scraper used by Plex Media comes from. It is an old prototype developed for get_iplayer. I found the repository on Github recently. I am still not a fan of this approach, though.

**Comment by primaeval** [comment]
At first I tried the \s pattern for whitespace including newlines but it didn't work for me in Highlights for <a\nhref. Any idea's why? A whitespace match should be enough to catch pretty printing.

Hopefully they won't tinker around with the ScrapeEpisodes pages for a while.

That's interesting about the scraper. Can you post a link.

**Comment by CaptainTK** [comment]
You are right. According to the Python documentation \s should also match \n. Strange that it didn't work for you.

See [here](http://lists.infradead.org/pipermail/get_iplayer/2014-October/006303.html) for the scraper.

**Comment by primaeval** [comment]
Thanks. I just read a post saying they were going to open up the Nitro API to the public by the end of 2014. Maybe its a rounding error. ;)
