### ISSUE TITLE
update speed

### ISSUE THREAD

**Issue by primaeval** [vonH/plugin.video.iplayerwww#55]
The Kodi devs seem to take a long time to take in new updates. Is there somewhere we can petition them to hurry up?

**Comment by CaptainTK** [comment]
I assume they are just on vacation. No add-on has been updated since Dec 31 and I don't see what we could do.

The good news is: The PR for 1.3.1 was merged into the official repo two days ago. Usually ithe auto update arrived on my installation a day later or so. Let's hope this happens soon for 1.3.1 as well.

**Comment by primaeval** [comment]
Hopefully it was just holidays then.

Can you mark the addon as broken to get them to prioritise it?

**Comment by CaptainTK** [comment]
I don't think that would help. Marking it broken works the same way as an update, AFAIK.

**Comment by CaptainTK** [comment]
1.3.1 has been shipped via the official repo by now. Closing this issue.
