### ISSUE TITLE
feature request: Show live sport/misc programmes in search

### ISSUE THREAD

**Issue by beebl3brox** [vonH/plugin.video.iplayerwww#86]
Some live snooker and tennis events and also some misc live programming for example springwatch unsprung don't appear on a bbc channel but you can access them on the BBC sport and other bbc websites, would be nice to be able to see these in search, or under a separate "Live events" section.

**Comment by primaeval** [comment]
Have you got some example links? An index page that we could scrape would be best.

**Comment by CaptainTK** [comment]
The live streams are a bit of a hack at the moment. I don't think it would be possible to scrape them and I am afraid it will be the same for these special streams. To be more precise: I guess scraping them in Search will be straightforward, this is most likely just a different programme-type which we currently ignore. However, this just gets you a directory entry. I am skeptic it will be possible to get to the right streams, at least if the mechanism is the same as for live TV.

I am somewhat optimistic the situation will improve once DASH becomes the new standard at the Beeb and once Kodi supports DASH. The latter might be the bigger issue.

**Comment by CaptainTK** [comment]
I actually believe this was a misunderstanding. As the Olympics showed, there are some programmes which are broadcast live using Red Button channels. If these are advertised in Highlights or any other page that is reachable, they should also play since 2.4.0.

So for now, I believe this is fixed, @beebl3brox. If you come across the issue again, please reopen this issue and provide a link to the relevant URL. Thanks.
